//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipmentLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HP200")]
        public string LaserPrinter {
            get {
                return ((string)(this["LaserPrinter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HP200")]
        public string LabelPrinter {
            get {
                return ((string)(this["LabelPrinter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02")]
        public string PackageTypeCode {
            get {
                return ((string)(this["PackageTypeCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06")]
        public string ServiceNotificationCode {
            get {
                return ((string)(this["ServiceNotificationCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mobilfunkzubehör")]
        public string ServiceDescription {
            get {
                return ((string)(this["ServiceDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EUR")]
        public string CODAmountCurrencyCode {
            get {
                return ((string)(this["CODAmountCurrencyCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KGS")]
        public string ShipUnitOfMeasurementTypeCode {
            get {
                return ((string)(this["ShipUnitOfMeasurementTypeCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KG")]
        public string ShipUnitOfMeasurementTypeDescription {
            get {
                return ((string)(this["ShipUnitOfMeasurementTypeDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EPL")]
        public string LabelImageFormatCode {
            get {
                return ((string)(this["LabelImageFormatCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string LabelStockSizeHeight {
            get {
                return ((string)(this["LabelStockSizeHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string LabelStockSizeWidth {
            get {
                return ((string)(this["LabelStockSizeWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wegatrade GmbH")]
        public string ShipperName {
            get {
                return ((string)(this["ShipperName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mustafa Uyulan")]
        public string ShipperAttentionName {
            get {
                return ((string)(this["ShipperAttentionName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Piepersberg 23")]
        public string ShipperAddressLine {
            get {
                return ((string)(this["ShipperAddressLine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DE")]
        public string ShipperCountryCode {
            get {
                return ((string)(this["ShipperCountryCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+492126450100")]
        public string ShipperPhoneNumber {
            get {
                return ((string)(this["ShipperPhoneNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShipperStateProvinceCode {
            get {
                return ((string)(this["ShipperStateProvinceCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("info@wegatrade.de")]
        public string ShipperEmail {
            get {
                return ((string)(this["ShipperEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wegatrade GmbH")]
        public string ShipperFromName {
            get {
                return ((string)(this["ShipperFromName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mustafa Uyulan")]
        public string ShipperFromAttentionName {
            get {
                return ((string)(this["ShipperFromAttentionName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Piepersberg 23")]
        public string ShipperFromAddressLine {
            get {
                return ((string)(this["ShipperFromAddressLine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42653")]
        public string ShipperFromPostalCode {
            get {
                return ((string)(this["ShipperFromPostalCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solingen")]
        public string ShipperFromCity {
            get {
                return ((string)(this["ShipperFromCity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DE")]
        public string ShipperFromCountryCode {
            get {
                return ((string)(this["ShipperFromCountryCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+492126450100")]
        public string ShipperFromPhoneNumber {
            get {
                return ((string)(this["ShipperFromPhoneNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShipperFromStateProvinceCode {
            get {
                return ((string)(this["ShipperFromStateProvinceCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("info@wegatrade.de")]
        public string ShipperFromEmail {
            get {
                return ((string)(this["ShipperFromEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solingen")]
        public string ShipperCity {
            get {
                return ((string)(this["ShipperCity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42653")]
        public string ShipperPostalCode {
            get {
                return ((string)(this["ShipperPostalCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01")]
        public string ShipmentChargeType {
            get {
                return ((string)(this["ShipmentChargeType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ShipmentRequest")]
        public string ShipmentDescription {
            get {
                return ((string)(this["ShipmentDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string PrintBarcode {
            get {
                return ((string)(this["PrintBarcode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wwwcie.ups.com/webservices/Ship")]
        public string UPS_ShippingModule_ShipWebReference_ShipService_Test {
            get {
                return ((string)(this["UPS_ShippingModule_ShipWebReference_ShipService_Test"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string LLPreview {
            get {
                return ((string)(this["LLPreview"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string PrintTurnIn {
            get {
                return ((string)(this["PrintTurnIn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wwwcie.ups.com/webservices/Void")]
        public string UPS_ShippingModule_VoidWebReference_VoidService_Test {
            get {
                return ((string)(this["UPS_ShippingModule_VoidWebReference_VoidService_Test"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string OpenNotepadOnException {
            get {
                return ((string)(this["OpenNotepadOnException"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string Retries {
            get {
                return ((string)(this["Retries"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Projects\\Wegatrade\\WegaShipment\\ShipmentModule\\bin\\Debug\\Downloads")]
        public string DownloadFolder {
            get {
                return ((string)(this["DownloadFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Projects\\Wegatrade\\WegaShipment\\ShipmentModule\\bin\\Debug\\Log")]
        public string LogFolder {
            get {
                return ((string)(this["LogFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Projects\\Wegatrade\\WegaShipment\\ShipmentModule\\bin\\Debug\\Reports\\PrintHtml.lst" +
            "")]
        public string FileLLHtml {
            get {
                return ((string)(this["FileLLHtml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Projects\\Wegatrade\\WegaShipment\\ShipmentModule\\bin\\Debug\\Reports\\PrintSummaryU" +
            "PS.lst")]
        public string FileLLSummaryUPS {
            get {
                return ((string)(this["FileLLSummaryUPS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cig.dhl.de/services/sandbox/soap")]
        public string DHL_ShippingModule_ShipWebReference_ShipService_Test {
            get {
                return ((string)(this["DHL_ShippingModule_ShipWebReference_ShipService_Test"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8C8FDE8E6E0D5830")]
        public string UPS_AccessLicenseNumber {
            get {
                return ((string)(this["UPS_AccessLicenseNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26939V")]
        public string UPS_Username {
            get {
                return ((string)(this["UPS_Username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wegatrade13")]
        public string UPS_Password {
            get {
                return ((string)(this["UPS_Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("geschaeftskunden_api")]
        public string DHL_IntraShipUser {
            get {
                return ((string)(this["DHL_IntraShipUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dhl_ep_test1")]
        public string DHL_IntraShipPassword {
            get {
                return ((string)(this["DHL_IntraShipPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wegatrade")]
        public string DHL_CigUser {
            get {
                return ((string)(this["DHL_CigUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$SimWeg@!3")]
        public string DHL_CigPassword {
            get {
                return ((string)(this["DHL_CigPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Piepersberg")]
        public string ShipperStreet {
            get {
                return ((string)(this["ShipperStreet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public string ShipperStreetNr {
            get {
                return ((string)(this["ShipperStreetNr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6105760911")]
        public string DHL_EKP_Prod {
            get {
                return ((string)(this["DHL_EKP_Prod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DE814263581")]
        public string Shipper_VATID {
            get {
                return ((string)(this["Shipper_VATID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cig.dhl.de/services/production/soap")]
        public string DHL_ShippingModule_ShipWebReference_ShipService_Prod {
            get {
                return ((string)(this["DHL_ShippingModule_ShipWebReference_ShipService_Prod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000000008")]
        public string DHL_EKP_Test {
            get {
                return ((string)(this["DHL_EKP_Test"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mk@simetrix.eu")]
        public string DHL_Username {
            get {
                return ((string)(this["DHL_Username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ShipmentModule_2")]
        public string DHL_ApplicationsID {
            get {
                return ((string)(this["DHL_ApplicationsID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vqyv6bvCqmbUz58Ctf2uxprAvbaU4M")]
        public string DHL_Applicationstoken {
            get {
                return ((string)(this["DHL_Applicationstoken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wegatrade GmbH")]
        public string ShipperAccountOwner {
            get {
                return ((string)(this["ShipperAccountOwner"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("017087801")]
        public string ShipperAccountNumber {
            get {
                return ((string)(this["ShipperAccountNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34270024")]
        public string ShipperBankCode {
            get {
                return ((string)(this["ShipperBankCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Deutsche Bank AG Solingen")]
        public string ShipperBankName {
            get {
                return ((string)(this["ShipperBankName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DE71342700240017087801")]
        public string ShipperIban {
            get {
                return ((string)(this["ShipperIban"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEUTDEDB342")]
        public string ShipperBic {
            get {
                return ((string)(this["ShipperBic"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DHL_TestMode {
            get {
                return ((bool)(this["DHL_TestMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public string Paket_Length {
            get {
                return ((string)(this["Paket_Length"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string Paket_Width {
            get {
                return ((string)(this["Paket_Width"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public string Paket_Height {
            get {
                return ((string)(this["Paket_Height"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Projects\\Wegatrade\\WegaShipment\\ShipmentModule\\bin\\Debug\\Reports\\PrintPdf.lst")]
        public string FileLLPdf {
            get {
                return ((string)(this["FileLLPdf"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("de-DE")]
        public string DatabaseCulture {
            get {
                return ((string)(this["DatabaseCulture"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dhl.pdf")]
        public string DHL_PDF_Filename {
            get {
                return ((string)(this["DHL_PDF_Filename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01")]
        public string DHL_PartnerID {
            get {
                return ((string)(this["DHL_PartnerID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("expdoc.pdf")]
        public string DHL_ExportDocument_Filename {
            get {
                return ((string)(this["DHL_ExportDocument_Filename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Projects\\Wegatrade\\WegaShipment\\ShipmentModule\\bin\\Debug\\Reports\\PrintExportDo" +
            "cPdf.lst")]
        public string FileLLExportDocumentPdf {
            get {
                return ((string)(this["FileLLExportDocumentPdf"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://onlinetools.ups.com/webservices/Ship")]
        public string UPS_ShippingModule_ShipWebReference_ShipService_Prod {
            get {
                return ((string)(this["UPS_ShippingModule_ShipWebReference_ShipService_Prod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://onlinetools.ups.com/webservices/Void")]
        public string UPS_ShippingModule_VoidWebReference_VoidService_Prod {
            get {
                return ((string)(this["UPS_ShippingModule_VoidWebReference_VoidService_Prod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UPS_TestMode {
            get {
                return ((bool)(this["UPS_TestMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Projects\\Wegatrade\\WegaShipment\\ShipmentModule\\bin\\Debug\\Reports\\PrintPic.lst")]
        public string FileLLPic {
            get {
                return ((string)(this["FileLLPic"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0rTJDg")]
        public string LLLicenseInfo {
            get {
                return ((string)(this["LLLicenseInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string LLDesign {
            get {
                return ((string)(this["LLDesign"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Projects\\Wegatrade\\WegaShipment\\ShipmentModule\\bin\\Debug\\Reports\\PrintListUPS." +
            "lst")]
        public string FileLLListUPS {
            get {
                return ((string)(this["FileLLListUPS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Projects\\Wegatrade\\WegaShipment\\ShipmentModule\\bin\\Debug\\Reports\\PrintListDHL." +
            "lst")]
        public string FileLLListDHL {
            get {
                return ((string)(this["FileLLListDHL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Projects\\Wegatrade\\WegaShipment\\ShipmentModule\\bin\\Debug\\Reports\\PrintSummaryD" +
            "HL.lst")]
        public string FileLLSummaryDHL {
            get {
                return ((string)(this["FileLLSummaryDHL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("manifest.pdf")]
        public string DHL_Manifest_Filename {
            get {
                return ((string)(this["DHL_Manifest_Filename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Projects\\Wegatrade\\WegaShipment\\ShipmentModule\\bin\\Debug\\Reports\\PrintManifest" +
            "edDHL.lst")]
        public string FileLLManifestedDHL {
            get {
                return ((string)(this["FileLLManifestedDHL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03")]
        public string DHL_PartnerCode_NAT {
            get {
                return ((string)(this["DHL_PartnerCode_NAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02")]
        public string DHL_PartnerCode_INT {
            get {
                return ((string)(this["DHL_PartnerCode_INT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02")]
        public string DHL_PartnerCode_BP_INT {
            get {
                return ((string)(this["DHL_PartnerCode_BP_INT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01")]
        public string DHL_PartnerCode_TestMode {
            get {
                return ((string)(this["DHL_PartnerCode_TestMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double PauschalBetrag {
            get {
                return ((double)(this["PauschalBetrag"]));
            }
        }
    }
}
